INSERT INTO MEMBERS(ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PICTURE, IS_ACTIVE) VALUES (1, 'Sasa', 'Fajkovic', '1989-05-10', NULL, TRUE);
INSERT INTO MEMBERS(ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PICTURE, IS_ACTIVE) VALUES (2, 'Foo', 'Fighters', '1989-05-10', NULL, TRUE);
INSERT INTO MEMBERS(ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PICTURE, IS_ACTIVE) VALUES (3, 'Iron', 'Maiden', '1989-05-10', NULL, FALSE);
INSERT INTO MEMBERS(ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PICTURE, IS_ACTIVE) VALUES (4, 'Deep', 'Purple', '1989-05-10', NULL, FALSE);
INSERT INTO MEMBERS(ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, PICTURE, IS_ACTIVE) VALUES (5, 'Pink', 'Floyd', '1989-05-10', NULL, TRUE);